name: UltimateCaptcha
main: SoyDavs\UltimateCaptcha\Main
version: 1.0.0
api: [5.0.0]
author: SoyDavs
description: A super secure captcha plugin for PocketMine-MP 5

depends:
  - FormsUI

commands:
  captcha:
    description: "Forces the captcha form to appear again"
    usage: "/captcha"
    permission: "ultimatecaptcha.command.captcha"

permissions:
  ultimatecaptcha.command.captcha:
    default: op
    description: "Allows a player to use the /captcha command"
