# UltimateCaptcha by SoyDavs
# All settings are customizable

Captcha:
  ShowOnEveryJoin: false
  MaxAttempts: 3
  NotifyOnSuspicious: true
  CaptchaType: "TEXT"
  RandomTextLength: 6
  UseCaseSensitive: true
  ResendFormDelay: 10
  BlockMovement: true
  BlockInteract: true
  BlockCommands: true
  BlockChat: true

Messages:
  Title: "§l§bUltimateCaptcha"
  Description: "Please complete this captcha to unlock!"
  WrongAnswer: "§cIncorrect captcha. Try again!"
  CorrectAnswer: "§aYou have passed the captcha!"
  SuspiciousAlert: "§cYou have exceeded the maximum attempts!"
  BlockedInteract: "§cYou must complete the captcha first!"

Discord:
  WebhookURL: "https://discord.com/api/webhooks/XXXXX/XXXXX"
  SuspiciousMessage: "Player {player} might be a bot! Too many captcha failures."
